language: php

php:
    - '7.1'
    - '7.2'

before_install:
    - pecl install -f svm
    - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
    - composer install

script:
    - composer analyze
    - composer test
